# -*- coding: utf-8 -*-
"""ShivaniAnand_B4_b1_SPL_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yuk37Q1gEarRBXPwhNam0_yynVfcGurt
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/AI_Job_Market_Trends_2026.csv')
df

"""# **Dataset Loading and Exploration**"""

df.describe()

df.info()

df.isnull().sum()

"""# **Data Preprocessing**"""

# Remove duplicates
df.drop_duplicates(inplace=True)

# Drop ID column
df.drop("job_id", axis=1, inplace=True)

# Fill missing values (numeric + categorical)
categorical_cols = df.select_dtypes(include=["object", "category"]).columns
numeric_cols = df.select_dtypes(include=["number"]).columns

df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

for col in categorical_cols:
    if df[col].dtype.name == "category":
        df[col] = df[col].cat.add_categories("Unknown")
    df[col] = df[col].fillna("Unknown")

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='company_size', data=df) # Changed 'NObeyesdad' to 'company_size'
plt.title('Distribution of Company Size') # Updated title for clarity
plt.show()

plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Feature Correlation Heatmap')
plt.show()

sns.countplot(x='years_experience', data=df)
plt.title('Years of Experience Distribution')
plt.show()

df["salary_class"] = pd.qcut(
    df["salary"],
    q=3,
    labels=["Low", "Medium", "High"]
)

# Drop original salary
df.drop("salary", axis=1, inplace=True)

"""# **Train and test**"""

X = df.drop("salary_class", axis=1)
y = df["salary_class"]

X = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

trained_models = {}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    trained_models[name] = model

from sklearn.metrics import accuracy_score, roc_curve, auc
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import numpy as np

# Convert target into binary format for ROC (multi-class)
classes = y.unique()
y_bin = label_binarize(y, classes=classes)

# Use SAME train-test split (outside loop)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=7
)

# Scale data (important)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

plt.figure(figsize=(8, 6))

for name, model in models.items():

    # Set parameters
    if "Random" in name:
        model.set_params(n_estimators=50, max_depth=5, random_state=7)
    elif "Decision" in name:
        model.set_params(max_depth=4, random_state=7)

    # Train model
    model.fit(X_train, y_train)

    # Predictions
    y_pred = model.predict(X_test)

    # ✅ Accuracy (correct way)
    acc = accuracy_score(y_test, y_pred)
    print(name, "Accuracy:", round(acc, 2))

    # ✅ ROC Curve (only if probability exists)
    if hasattr(model, "predict_proba"):

        y_score = model.predict_proba(X_test)

        # Compute ROC for each class
        for i in range(len(classes)):
            fpr, tpr, _ = roc_curve(
                (y_test == classes[i]).astype(int),
                y_score[:, i]
            )
            roc_auc = auc(fpr, tpr)

            plt.plot(fpr, tpr,
                     label=f"{name} (Class {classes[i]}) AUC={roc_auc:.2f}")

# Random line
plt.plot([0, 1], [0, 1], 'k--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve (Multi-class)")
plt.legend()
plt.show()

from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
from sklearn.model_selection import train_test_split

results = []

_, _, _, y_test_consistent = train_test_split(X, y, test_size=0.2, random_state=42)

for name, model in trained_models.items():
    y_pred = model.predict(X_test_scaled)

    # Use y_test_consistent instead of the overwritten y_test
    acc = accuracy_score(y_test_consistent, y_pred)

    print(f"\n{name}")
    print("Accuracy:", acc)
    print(classification_report(y_test_consistent, y_pred))

    results.append({"Model": name, "Accuracy": acc})

results_df = pd.DataFrame(results)
print("\nModel Comparison:\n", results_df)

best_model_name = results_df.sort_values(by="Accuracy", ascending=False).iloc[0]["Model"]

print("Best Model:", best_model_name)

best_model = trained_models[best_model_name]

from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split


_, _, _, y_test_consistent = train_test_split(X, y, test_size=0.2, random_state=42)

y_pred = best_model.predict(X_test_scaled)

print("Confusion Matrix:\n", confusion_matrix(y_test_consistent, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

_, _, _, y_test_consistent = train_test_split(X, y, test_size=0.2, random_state=42)

y_pred = best_model.predict(X_test_scaled)

cm = confusion_matrix(y_test_consistent, y_pred)

plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title(f'Confusion Matrix ({best_model_name})') # Use the actual best model's name
plt.show()

from sklearn.ensemble import VotingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost import XGBClassifier

# Using relevant existing numeric columns for GUI input
gui_columns = ['years_experience', 'skills_python', 'job_openings', 'job_posting_year']

# Use the 'salary_class' as the target variable, which was previously created
y_gui = df['salary_class']

X_gui = df[gui_columns]
X_train_gui, X_test_gui, y_train_gui, y_test_gui = train_test_split(X_gui, y_gui, test_size=0.2, random_state=7)

scaler_gui = StandardScaler()
X_train_scaled_gui = scaler_gui.fit_transform(X_train_gui)

hybrid_model_gui = VotingClassifier(
    estimators=[('lr', LogisticRegression()), ('svm', SVC(probability=True)), ('xgb', XGBClassifier())],
    voting='soft'
)
hybrid_model_gui.fit(X_train_scaled_gui, y_train_gui)

import pickle
from google.colab import files

# Save best model
with open("salary_classifier_model.pkl", "wb") as f:
    pickle.dump(best_model, f)

# Save scaler
with open("salary_classifier_scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

# Save feature column names
with open("salary_classifier_features.pkl", "wb") as f:
    pickle.dump(X.columns.tolist(), f)

print("Pickle files saved successfully!")

files.download("salary_classifier_model.pkl")
files.download("salary_classifier_scaler.pkl")
files.download("salary_classifier_features.pkl")